content/urls.py
from django.urls import path
from content.views import home, contact
app_name ="content"
urlpatterns =[
    path("home/", home, name="home"),
    path("contact/", contact, name="contact"),
   
    
]

news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("content.urls", namespace="content")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class NewsStatus(models.TextChoices):
    PUBLIC = ("public", "Public")
    PRIVATE = ("private", "Private")
class PositionStatus(models.TextChoices):
    NORMAL = ("normal", "Normal")
    FIRST = ("first", "First")
    SECOND = ("second", "Second")
    THIRD = ("third", "Third")
    FORTH = ("forth", "Forth")
class ProvinceStatus(models.TextChoices):
    ALL = ("all", "All")
    ONE = ("one", "One")
    SECOND = ("second", "Second")
    THIRD = ("third", "Third")
    FORTH = ("forth", "Forth")
    FIFTH = ("fifth", "Fifth")
    SIX = ("six", "Six")
    SEVEN = ("SEVEN", "Seven")
class Category(models.Model):
    category_name=models.TextField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.category_name
    
class News(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    sub_description = models.TextField( blank=True, null=True)
    description = RichTextField()
    picture = models.ImageField(upload_to="news_image/", blank=True, null=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    view_count = models.IntegerField(default=0)

    news_postion = models.CharField(
        max_length=100,
        choices=PositionStatus.choices,
        default=PositionStatus.NORMAL
    )
    province = models.CharField(
        max_length=100,
        choices=ProvinceStatus.choices,
        default=ProvinceStatus.ALL
    )
    status = models.CharField(
        max_length=100,
        choices=NewsStatus.choices,
        default=NewsStatus.PRIVATE
    )

    
    class Meta:
        verbose_name = "News"
        verbose_name_plural = "Newss"

    def __str__(self):
        return str(self.id)
    
    @property
    def like_count(self):
        return self.like_set.filter(is_liked=True).count()
    @property   
    def comment_count(self):
        return self.comment_set.count()
    
class Like(models.Model):
    is_liked = models.BooleanField(default=False)
    post = models.ForeignKey(News, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

    
   
    
class Comment(models.Model):
    text = models.CharField(max_length=150)
    post = models.ForeignKey(News, on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    
class Organization(models.Model):
    org_name = models.CharField(max_length=100, blank=True, null=True)
    logo = models.ImageField(upload_to="logo_image/", blank=True, null=False)
    address = models.CharField(max_length=100, blank=True, null=True)
    contact = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    facebook = models.CharField(max_length=100, blank=True, null=True)
    twiter = models.CharField(max_length=100, blank=True, null=True)
    instagram = models.CharField(max_length=100, blank=True, null=True)
    linkdin = models.CharField(max_length=100, blank=True, null=True)
    youtube = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return str(self.id)
class Contact(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=100, blank=True, null=False)
    subject = models.CharField(max_length=100, blank=True, null=True)
    message = models.TextField(max_length=100, blank=True, null=True)
    

    def __str__(self):
        return str(self.id)

content/views.py
from django.shortcuts import render
from django.http import HttpResponse
from content.models import News,Organization
# Create your views here.

def home(request):
    data= News.objects.filter(news_postion="first").filter(status="public").order_by("-id").first()
    second_data= News.objects.filter(news_postion="second").filter(status="public").order_by("-id").first()
    third_data= News.objects.filter(news_postion="third").filter(status="public").order_by("-id").first()
    fourth_data= News.objects.filter(news_postion="forth").filter(status="public").order_by("-id").first()
    org = Organization.objects.order_by('-id').first()
    
    context={
        "data":data,
        "org":org,
        "second_data":second_data,
        "third_data": third_data,
        "fourth_data": fourth_data
    }
    return render(request,"index.html", context)

def contact(request):
    org = Organization.objects.order_by('-id').first()
    
    context={
       
        "org":org
    }
    return render(request, "contact.html",context)

content/templates/contact.html
{% extends 'base_site.html' %}
{% block content %}

 <!-- Breadcrumb Start -->
 <div class="breadcrumb-wrap">
    <div class="container">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'content:home' %}">Home</a></li>
            <li class="breadcrumb-item active">Contact</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Contact Start -->
<div class="contact">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="contact-form">
                    <form>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <input type="text" class="form-control" placeholder="Your Name" />
                            </div>
                            <div class="form-group col-md-6">
                                <input type="email" class="form-control" placeholder="Your Email" />
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Subject" />
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" rows="5" placeholder="Message"></textarea>
                        </div>
                        <div><button class="btn" type="submit">Send Message</button></div>
                    </form>
                </div>
            </div>
            <div class="col-md-4">
                <div class="contact-info">
                    <h3>Get in Touch</h3>
                    <p class="mb-4">The contact form is currently inactive. Get a functional and working contact form with Ajax & PHP in a few minutes. Just copy and paste the files, add a little code and you're done. <a href="https://htmlcodex.com/contact-form">Download Now</a>.</p>
                    <h4><i class="fa fa-map-marker"></i>{{org.address}}</h4>
                    <h4><i class="fa fa-envelope"></i>{{org.email}}</h4>
                    <h4><i class="fa fa-phone"></i>{{org.contact}}</h4>
                    <div class="social">
                            <a href="{{org.twiter}}"><i class="fab fa-twitter"></i></a>
                            <a href="{{org.facebook}}"><i class="fab fa-facebook-f"></i></a>
                            <a href="{{org.linkdin}}"><i class="fab fa-linkedin-in"></i></a>
                            <a href="{{org.instagram}}"><i class="fab fa-instagram"></i></a>
                            <a href="{{org.youtube}}"><i class="fab fa-youtube"></i></a>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->


{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Bootstrap News Template - Free HTML Templates" name="keywords">
    <meta content="Bootstrap News Template - Free HTML Templates" name="description">
    <title>
        {% if title %}
            {{title}}
        {% else %}
            sarbajanik news
        {% endif %}
    </title>
    {% block stylesheet %}
        
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap" rel="stylesheet"> 

        <!-- CSS Libraries -->
        <link href="{% static 'css1/style.css' %}" rel="stylesheet">
        <link href="{% static 'css1/icon.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/main.css' %}" rel="stylesheet">
        <link href="{% static 'css/mycss.css' %}" rel="stylesheet">
        
    {% endblock stylesheet %}
</head>
<body>
    
        {% block main %}

        {% endblock main %}

    
    {% block script %}
        
        <!-- JavaScript Libraries -->
        <script src="{% static 'js1/jquery1.js' %}"></script>
        <script src="{% static 'js1/script.js' %}"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>
        <script src="{% static 'js1/icon.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>



    {% endblock script %}
</body>
</html>

templates/base_site.html
{% extends 'base.html' %}
{% block main %}
    {% include 'navbar.html' %}
    {% block content %}
    
    {% endblock content %}
    {% include 'footer.html' %}
{% endblock main%}

templates/footer.html
 <!-- Footer Start -->
 <div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="footer-widget">
                    <h3 class="title">Get in Touch</h3>
                    <div class="contact-info">
                        <p><i class="fa fa-map-marker"></i>{{org.address}}</p>
                        <p><i class="fa fa-envelope"></i>{{org.email}}</p>
                        <p><i class="fa fa-phone"></i>{{org.contact}}</p>
                        <div class="social">
                            <a href="{{org.twiter}}"><i class="fab fa-twitter"></i></a>
                            <a href="{{org.facebook}}"><i class="fab fa-facebook-f"></i></a>
                            <a href="{{org.linkdin}}"><i class="fab fa-linkedin-in"></i></a>
                            <a href="{{org.instagram}}"><i class="fab fa-instagram"></i></a>
                            <a href="{{org.youtube}}"><i class="fab fa-youtube"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-3 col-md-6">
                <div class="footer-widget">
                    <h3 class="title">Useful Links</h3>
                    <ul>
                        <li><a href="#">Lorem ipsum</a></li>
                        <li><a href="#">Pellentesque</a></li>
                        <li><a href="#">Aenean vulputate</a></li>
                        <li><a href="#">Vestibulum sit amet</a></li>
                        <li><a href="#">Nam dignissim</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="footer-widget">
                    <h3 class="title">Quick Links</h3>
                    <ul>
                        <li><a href="#">Lorem ipsum</a></li>
                        <li><a href="#">Pellentesque</a></li>
                        <li><a href="#">Aenean vulputate</a></li>
                        <li><a href="#">Vestibulum sit amet</a></li>
                        <li><a href="#">Nam dignissim</a></li>
                    </ul>
                </div>
            </div>
            
            <div class="col-lg-3 col-md-6">
                <div class="footer-widget">
                    <h3 class="title">Floow Us</h3>
                    <div class="newsletter">
                        <iframe class="embed-responsive-item"
                        src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fprofile.php%3Fid%3D61555343035989&tabs&width=320&height=130&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=false&appId"
                        width="340" height="130" style="border:none;overflow:hidden" scrolling="no" frameborder="0"
                        allowfullscreen="true"
                        allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Footer Bottom Start -->
<div class="footer-bottom">
    <div class="container">
        <div class="row">
            <div class="col-md-6 copyright">
                <p>Copyright &copy; <a href="" class="font_color">Sarbajanik Newss</a>. All Rights Reserved</p>
            </div>

            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
            <div class="col-md-6 template-by">
                <p>Designed By <a href="https://codebloominfotech.github.io/" class="font_color">CodeBloominfotech</a></p>
            </div>
        </div>
    </div>
</div>
<!-- Footer Bottom End -->

<!-- Back to Top -->
<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

templates/navbar.html
 <!-- Top Bar Start -->
 <div class="top-bar">
  <div class="container ">
      <div class="row">
          <div class="col-md-6">
              <div class="tb-contact">
                  <p><i class="fas fa-envelope"></i>{{org.email}}</p>
                  <p><i class="fas fa-phone-alt"></i>{{org.contact}}</p>
              </div>
          </div>
          <div class="col-md-6">
              <div class="tb-menu">
                  <a href="">About</a>
                  <a href="">Privacy</a>
                  <a href="">Terms</a>
                  <a href="">Contact</a>
              </div>
          </div>
      </div>
  </div>
</div>
<!-- Top Bar Start -->

<!-- Brand Start -->
<div class="brand">
  <div class="container">
      <div class="row align-items-center">
          <div class="col-lg-4 col-md-4">
              <div class="b-ads">
                  <span style=" padding: 1px 0px 0px 6px; border-radius:3px; height:50px; background-color: #DFF5FF; width:175px; display:block;">
                      <iframe scrolling="no" border="0" frameborder="0" marginwidth="0" marginheight="0" allowtransparency="true" src="https://www.ashesh.com.np/linknepali-time.php?time_only=no&font_color=666666&aj_time=yes&font_size=12&line_brake=1&api=510145o085" width="175" height="45"></iframe></span>
                  
                  
              </div>
          </div>
          <div class="col-lg-4 col-md-4 ">
              <div class="b-logo">
                  <a href="index.html">
                      <img src="{{org.logo.url}}" alt="Logo">
                      
                  </a>
              </div>
          </div>
          
          <div class="col-lg-4 col-md-4">
              <div class="b-search">
                  <input type="text" placeholder="Search">
                  <button><i class="fa fa-search"></i></button>
              </div>
          </div>
      </div>
  </div>
</div>
<!-- Brand End -->

<!-- Nav Bar Start -->
<div class="nav-bar">
  <div class="container">
      <nav class="navbar navbar-expand-md bg-dark navbar-dark">
          <a href="#" class="navbar-brand">MENU</a>
          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
              <div class="navbar-nav mr-auto">
                  <a href="{% url 'content:home' %}" class="nav-item nav-link  ">होम </a>
                  <a href="#" class="nav-item nav-link  ">समाचार </a>
                  
                  <a href="#" class="nav-item nav-link ">चर्चामा </a>
                  <a href="#" class="nav-item nav-link ">राजनिती </a>
                  <a href="#" class="nav-item nav-link ">अर्थ </a>
                  <a href="#" class="nav-item nav-link ">मनाेरंजन </a>
                  <a href="#" class="nav-item nav-link ">खेलकुद </a>
                  <a href="#" class="nav-item nav-link ">प्रविधिक</a>
                  
                  <div class="nav-item dropdown">
                      <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">प्रदेश</a>
                      <div class="dropdown-menu">
                          <a href="#" class="dropdown-item">प्रदेश न.१</a>
                          <a href="#" class="dropdown-item">प्रदेश न.२ </a>
                          <a href="#" class="dropdown-item">प्रदेश न.३ </a>
                          <a href="#" class="dropdown-item">प्रदेश न.४ </a>
                          <a href="#" class="dropdown-item">प्रदेश न.५ </a>
                          <a href="#" class="dropdown-item">प्रदेश न.६ </a>
                          <a href="#" class="dropdown-item">प्रदेश न.७ </a>
                      </div>
                  </div>
                  <a href="#" class="nav-item nav-link ">बिचार</a>
                  
                  <a href="#" class="nav-item nav-link">अन्तरष्ट्रिय</a>
                  <a href="#" class="nav-item nav-link">अन्य</a>
                  <a href="#" class="nav-item nav-link">अन्तर्वाता/भिडियाे</a>
                  
                  <a href="{% url 'content:contact' %}" class="nav-item nav-link">सम्पर्क</a>
              </div>
              <div class="social ml-auto">
                  <a href="{{org.twiter}}"><i class="fab fa-twitter"></i></a>
                  <a href="{{org.facebook}}"><i class="fab fa-facebook-f"></i></a>
                  <a href="{{org.linkdin}}"><i class="fab fa-linkedin-in"></i></a>
                  <a href="{{org.instagram}}"><i class="fab fa-instagram"></i></a>
                  <a href="{{org.youtube}}"><i class="fab fa-youtube"></i></a>
              </div>
          </div>
      </nav>
  </div>
</div>
<!-- Nav Bar End -->